import React, { useEffect, useState } from 'react';

const Warningmessage = () => {
  const [showModal, setShowModal] = useState(true);

  useEffect(() => {
    setShowModal(true);
  }, []);
  if (!showModal) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black bg-opacity-70 flex items-center justify-center p-4">
      <div className="bg-[#1F2937] text-white rounded-lg shadow-lg max-w-md w-full p-6 space-y-4">
        <h2 className="text-xl font-semibold text-yellow-400">⚠️ AI Disclaimer</h2>
        <p className="text-sm">
          The result generated by the AI may contain serious issues. Please verify outputs carefully before using them in production or important environments.
        </p>
        <button
          onClick={() => setShowModal(false)}
          className="w-full bg-blue-600 hover:bg-blue-700 text-white py-2 rounded-md text-sm transition-colors"
        >
          Continue
        </button>
      </div>
    </div>
  );
};

export default Warningmessage;
